### ISSUE TITLE
Support Multiple Shifted Args (for method modifiers)

### ISSUE THREAD

**Issue by danschmidt5189** [mauke/Function-Parameters#23]
It would be nice if F::P offered a shortcut for working with Moose's `around` modifier, e.g.:

``` perl
package My::FP;
use Function::Parameters;
sub import {
    Function::Parameters->import({
        ...
        decorator => { shift => [qw($orig $self)], ... },
    });
}

package Some::Role;
use Moose::Role;
use My::FP;
around some_sub => decorator (@args) {
    # $orig *and* $self already shifted off
};
```

(Right now you're only able to shift off a single argument.)

**Comment by dstroma** [comment]
I would like to see this as well.

A simpler example...

```
use Function::Parameters { pair_function => { defaults => 'function_strict', shift => [qw($x $y)] }};
pair_function swap {
  return ($y, $x);
}

pair_function multiply {
  return $x * $y;
}

pair_function marry {
  say "I now pronounce $x and $y husband and wife!";
}
```

**Comment by tobyink** [comment]
This can be done in Kavorka. Probably needs to be made easier though.

```perl
use v5.14;
use warnings;
use Kavorka ();

# This would typically be in an external file.
BEGIN {
  package My::Function::Pair;
  use Moo;
  with 'Kavorka::Sub';
  sub default_invocant {
    require Kavorka::Parameter;
    return (
      'Kavorka::Parameter'->new(name => '$x', traits => { invocant => 1 }),
      'Kavorka::Parameter'->new(name => '$y', traits => { invocant => 1 }),
    );
  }
};

use Kavorka '-default', pair_function => { implementation => 'My::Function::Pair' };

# This function uses $x and $y defined above.
pair_function marry {
  say "I now pronounce $x and $y husband and wife!";
  say for @_;
}

marry("Bob", "Alice", "Those two were shifted off.");

# This one overrides $x and $y using its own variable names.
pair_function marry2 ($husband, $wife: ...) {
  say "I now pronounce $husband and $wife husband and wife!";
  say for @_;
}

marry2("Dave", "Carol", "Those two were shifted off.");
```

**Comment by sergeykolychev** [comment]
@tobyink 
Hello Toby,
Kavorka at this point is a bit on heavy side. I looked at all three offerings on CPAN and elected Function::Parameters to be a part of my project just because I want my code to be as light, dependency free and fast a possible
(I use Mouse anyway for OOP so type checking goes in for free).
Imo Kavorka needs to slim down to be competitive with other offerings. 
I only need "parameters checking", nothing more. I do not really want to load 68 pms and force users of my package to install all of them as well.

developer@devbox:~$ perl -MDevel::EndStats -MFunction::Parameters -e1

# Start stats from Devel::EndStats:
# Program runtime duration: 2.752ms
# Total number of required files loaded: 3
# Total number of required lines loaded: 1516
# End of stats
developer@devbox:~$ perl -MDevel::EndStats -MKavorka -e1

# Start stats from Devel::EndStats:
# Program runtime duration: 64.292ms
# Total number of required files loaded: 68
# Total number of required lines loaded: 26899
# End of stats
developer@devbox:~$ perl -MDevel::EndStats -MMethod::Signatures -e1

# Start stats from Devel::EndStats:
# Program runtime duration: 24.949ms
# Total number of required files loaded: 37
# Total number of required lines loaded: 13278
# End of stats

**Comment by mauke** [comment]
This is now possible with version 2 (already released to CPAN).
